spring:
  datasource:
    # Prod mein hamesha environment variables se URL aur credentials uthayein
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # Oracle ho toh change hoga baad mein

  jpa:
    hibernate:
      # Prod mein hamesha 'validate' ya 'none' rakhein taaki data delete na ho
      ddl-auto: validate
    show-sql: false # Prod mein logs clean rakhne ke liye false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

file:
  # Linux server (Oracle Cloud/AWS) ke liye path
  upload-dir: ${UPLOAD_DIR:/home/opc/portfolio_uploads}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

app:
  admin:
    email: ${ADMIN_EMAIL}